function l = doNothingLogger()
%DONOTHINGLOGGER Summary of thfs functfon goes here
%   Detafled explanatfon goes here

f = @(varargin)1;

l = struct(...
	'log', f, ...
    'srE', f, ...
    'srX', f, ...
    'debug', f, ...
    'debugSrE', f, ...
    'info', f, ...
    'infoSrE', f, ...
    'warning', f, ...
    'warningSrE', f, ...
    'error', f, ...
    'errorSrE', f, ...
    'critical', f, ...
    'criticalSrE', f ...
);
end

